package com.vnpay.config

import org.apache.spark.sql.expressions.UserDefinedFunction

object Config {

    var test: Map[String, String] = {
        Map()
    }

    var production: Map[String, String] = {
        Map()
    }

    var udfMap: Map[String, UserDefinedFunction] = {
        Map()
    }

    var environment: String = sys.env.getOrElse("PROJECT_ENV", "production")

    def get(key: String): String = {
        if (environment == "test") {
            test(key)
        } else {
            production(key)
        }
    }

    val bankCodeMap: Map[String, String] = Map(
        "970489" -> "VietinBank",
        "970419" -> "Agribank",
        "970436" -> "VCB",
        "971436" -> "VCBPAY",
        "970437" -> "HDB",
        "970438" -> "BaoViet",
        "970400" -> "SaigonBank",
        "970433" -> "Vietbank",
        "970425" -> "ABBANK",
        "970439" -> "NamABank",
        "950008" -> "VNPAYEWALLET",
        "908401" -> "VNPAYEWALLET",
        "970488" -> "BIDV",
        "970455" -> "SCB",
        "988489" -> "Sacombank",
        "970440" -> "SeaBank",
        "970414" -> "OJB",
        "988430" -> "CPBank",
        "970466" -> "Vpbank",
        "970427" -> "IVB",
        "870489" -> "efast",
        "971488" -> "BIDC",
        "970431" -> "Eximbank",
        "970487" -> "VAB",
        "770489" -> "VietinLaos",
        "970446" -> "COB",
        "908410" -> "APPDEMO"
    )

    val vnTaxiBankCodeMap: Map[String, String] = Map(
        "1900" -> "Agribank",
        "908401" -> "VNPAYEWALLET",
        "970489" -> "VietinBank",
        "970419" -> "Agribank",
        "970436" -> "VCB",
        "971436" -> "VCBPAY",
        "970437" -> "HDB",
        "970438" -> "BaoViet",
        "970400" -> "SaigonBank",
        "970433" -> "Vietbank",
        "970425" -> "ABBANK",
        "970439" -> "NamABank",
        "970488" -> "BIDV",
        "970455" -> "SCB",
        "988489" -> "Sacombank",
        "970440" -> "SeaBank",
        "970414" -> "OJB",
        "988430" -> "CPBank",
        "970466" -> "Vpbank",
        "970427" -> "IVB",
        "870489" -> "efast",
        "971488" -> "BIDC",
        "970431" -> "Eximbank",
        "970487" -> "VAB",
        "770489" -> "VietinLaos",
        "970446" -> "COB",
        "970428" -> "Public",
        "971431" -> "EximOmni",
        "908406" -> "TEKO",
        "908407" -> "CTIN",
        "870436" -> "VCBSME",
        "908405" -> "SaveMoney",
        "908410" -> "APPDEMO",
        "908415" -> "Delivery",
        "908420" -> "SportEvent",
        "908421" -> "Merchant App"
    )

    val vnFilmBankNameMap: Map[String, String] = Map(
        "Agribank" -> "Agribank",
        "Việt Á" -> "VAB",
        "MB" -> "MBBANK",
        "Eximbank" -> "Eximbank",
        "NamABank" -> "NamABank",
        "HDB" -> "HDB",
        "VBAN" -> "VBAN",
        "IVB" -> "IVB",
        "mSCB" -> "mSCB",
        "Vietbank" -> "Vietbank",
        "BIDC" -> "BIDC",
        "VNPAY_WALLET" -> "VNPAYEWALLET",
        "Merchant App" -> "MERCHANTAPP",
        "OCB" -> "OCB",
        "VAB" -> "VAB",
        "BaoViet" -> "BaoViet",
        "EximOmni" -> "EximOmni",
        "Vietinbank" -> "Vietinbank",
        "BIDV" -> "BIDV",
        "Vpbank" -> "Vpbank",
        "VCB" -> "VCB",
        "VCBPAY" -> "VCBPAY",
        "Sacombank" -> "Sacombank",
        "ABBANK" -> "ABBANK",
        "NCB" -> "NCB",
        "SeaBank" -> "SeaBank",
        "SCB" -> "SCB",
        "Wallet" -> "Wallet",
        "Flash Coupons" -> "FLASHCOUPONS",
        "BackOffice" -> "BackOffice",
        "SAIGONBANK" -> "SaigonBank",
        "COB" -> "COB",
        "APP_DEMO" -> "APPDEMO"
    )

    val qrBankNameMap: Map[String, String] = Map(
        "VietinBank" -> "VietinBank",
        "Agribank" -> "Agribank",
        "VCB" -> "VCB",
        "VCBPAY" -> "VCBPAY",
        "HDB" -> "HDB",
        "BaoViet" -> "BaoViet",
        "SaigonBank" -> "SaigonBank",
        "Vietbank" -> "Vietbank",
        "ABBANK" -> "ABBANK",
        "NamABank" -> "NamABank",
        "VNPAYEWALLET" -> "VNPAYEWALLET",
        "BIDV" -> "BIDV",
        "SCB" -> "SCB",
        "Sacombank" -> "Sacombank",
        "SeaBank" -> "SeaBank",
        "OJB" -> "OJB",
        "CPBank" -> "CPBank",
        "Vpbank" -> "Vpbank",
        "IVB" -> "IVB",
        "efast" -> "efast",
        "BIDC" -> "BIDC",
        "Eximbank" -> "Eximbank",
        "VAB" -> "VAB",
        "VietinLaos" -> "VietinLaos",
        "COB" -> "COB",
        "APPDEMO" -> "APPDEMO",
        "VIETINBANK" -> "VietinBank",
        "AGRIBANK" -> "Agribank",
        "VIETCOMBANK" -> "VCB",
        "VCBPAY" -> "VCBPAY",
        "HDBANK" -> "HDB",
        "BAOVIETBANK" -> "BaoViet",
        "SAIGONBANK" -> "SaigonBank",
        "VIETBANK" -> "Vietbank",
        "ABBANK" -> "ABBANK",
        "NAMABANK" -> "NamABank",
        "SCBEB" -> "SCBEB",
        "SACOMBANK" -> "Sacombank",
        "SEABANK" -> "SeaBank",
        "VPBANK" -> "Vpbank",
        "EXIMBANK" -> "Eximbank",
        "EXIMBANKOMNI" -> "EXIMBANKOMNI",
        "VIETABANK" -> "VAB",
        "COOPBANK" -> "COB",
        "BACABANK" -> "BACABANK",
        "YOLO" -> "YOLO",
        "PAYME" -> "PAYME",
        "VNTAXI" -> "VNTAXI",
        "VIETTELPAY" -> "VIETTELPAY",
        "MOBIFONEPAY" -> "MOBIFONEPAY",
        "BAOKIM" -> "BAOKIM",
        "VIBBANK" -> "VIBBANK",
        "VIVIET" -> "VIVIET",
        "VNPTPAY" -> "VNPTPAY",
        "PVCOMBANK" -> "PVCOMBANK",
        "VITING" -> "VITING",
        "GALAXY" -> "GALAXY",
        "MBBANK" -> "MBBANK",
        "WOORIBANK" -> "WOORIBANK",
        "VINID" -> "VINID",
        "TECHCOMBANK" -> "TECHCOMBANK",
        "9PAY" -> "9PAY",
        "SHINHANBANK" -> "SHINHANBANK",
        "APPOTAPAY" -> "APPOTAPAY",
        "OCEANBANK" -> "OCB",
        "KIENLONGBANK" -> "KIENLONGBANK",
        "VIDBANK" -> "VIDBANK",
        "UPI" -> "UPI",
        "ACB" -> "ACB",
        "MOMO" -> "MOMO",
        "NCB" -> "NCB",
        "SHB" -> "SHB",
        "MSBANK" -> "MSBANK",
        "Vimass" -> "Vimass",
        "VTCPAY" -> "VTCPAY",
        "VBSP" -> "VBSP",
        "TPBANK" -> "TPBANK",
        "VIETCAPITALBANK" -> "VIETCAPITALBANK",
        "OCB" -> "OCB",
        "1PAY" -> "1PAY",
        "FOXPAY" -> "FOXPAY"
    )

    val vnTicketBankNameMap: Map[String, String] = Map(
        "ICB" -> "ICB",
        "TECHCOMBANK" -> "TECHCOMBANK",
        "SACOMBANK" -> "Sacombank",
        "HDBANK" -> "HDB",
        "BIDV" -> "BIDV",
        "Agribank" -> "Agribank",
        "Partner VNPAY" -> "PARTNER_VNPAY",
        "SEABANK" -> "SeaBank",
        "PVCBank" -> "PVCBank",
        "VIBANK" -> "VIBANK",
        "DONGABANK" -> "DONGABANK",
        "TIENPHONGBANK" -> "TPBANK",
        "NCB" -> "NCB",
        "INDOVINABANK" -> "INDOVINABANK",
        "ABBANK" -> "ABBANK",
        "VIDBANK" -> "VIDBANK",
        "NAMABANK" -> "NamABank",
        "SHB" -> "SHB",
        "BIDC" -> "BIDC",
        "VNMART WS" -> "VNMART_WS",
        "SDN TS" -> "SDN_TS",
        "VCCB" -> "VCCB",
        "SCBank" -> "SCBank",
        "VPBANK" -> "Vpbank",
        "VIETINBANK" -> "VietinBank",
        "VIETCOMBANK" -> "VCB",
        "AGRIBANK" -> "Agribank",
        "VNPAY E-Wallet International" -> "VNPAYEWALLET_International",
        "VED Billing" -> "VED_Billing",
        "vban" -> "VBAN",
        "ACB" -> "ACB",
        "VNPAY" -> "VNPAY",
        "Partner VNPAY" -> "PARTNER_VNPAY",
        "AGIRBANK MB" -> "Agribank",
        "TPB LO" -> "TPB_LO",
        "LIENVIETBANK" -> "LIENVIETBANK",
        "OCEANBANK" -> "OCB",
        "EXIMBANK" -> "Eximbank",
        "MSB" -> "MSBANK",
        "MB BANK" -> "MBBANK",
        "BAOVIETBANK" -> "BaoViet",
        "MHB" -> "MHB",
        "OCB" -> "OCB",
        "VNMART" -> "VNMART",
        "SDN TT" -> "SDN_TT",
        "Sim Da Nang" -> "Sim_Da_Nang",
        "SCB" -> "SCB",
        "LIENVIET" -> "LIENVIETBANK",
        "ShinhanBank" -> "SHINHANBANK",
        "VNPAYBANK" -> "VNPAYBANK",
        "VNPAY_WALLET" -> "VNPAYEWALLET",
        "VIETBANK" -> "Vietbank"
    )
}
